# Generated by Django 3.0.2 on 2020-02-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='model_pic',
            field=models.ImageField(default='media/images/try.jpg', upload_to='media/images'),
        ),
    ]
