# Generated by Django 3.0.2 on 2020-02-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_model_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='model_pic',
            field=models.ImageField(default='e4bd55c5-8db4-4147-8d18-e5836cf12bca.jpg', upload_to='images/'),
        ),
    ]
